[package]
name = "chunk-by-line-ext"
version = "1.0.0"
edition = "2018"

[dependencies]
async-std = {version = "1.8.0", features = ["attributes", "unstable"]}
futures = "0.3.8"
anyhow = "1.0.37"
pin-project-lite = "0.2.4"
