[package]
name = "chunk-by-line-ext"
version = "1.0.0"
edition = "2018"

[dependencies]
futures = "0.3.8"
pin-project-lite = "0.2.4"

[dev-dependencies]
async-std = {version = "1.9.0", features = ["attributes", "unstable"]}
